/**
 * Build-time character source list — input FBXs the pipeline ingests.
 * Runtime metadata (scale, display name, thumbnails, etc.) lives in
 * src/fighter/characters.ts and is applied at runtime, not baked into GLBs.
 *
 * Each entry produces `public/assets/models/<id>.glb` via `bun run build:character`.
 *
 * Requirements for the input FBX:
 *   - Mixamo-rigged (bone names prefixed with `mixamorig:`)
 *   - T-pose action available (Mixamo's `mixamo.com` action at frame 1)
 *   - Weights auto-generated by mixamo.com
 */

import path from 'node:path';

const ASSETS_SOURCE = path.join(import.meta.dir, '..', 'assets', 'source');

export interface InjectedBone {
  name: string;
  parent: string;
  /** Head position in mesh-local space (metres) */
  head: [number, number, number];
  /** Tail position in mesh-local space (metres) */
  tail: [number, number, number];
  /**
   * If set, verts within this radius (metres) of the bone head get skin
   * weight via smoothstep falloff (partition of unity — all other bone
   * weights scale by 1-w so this bone dominates at center).
   * Omit for pure procedural helper bones with no mesh deformation.
   */
  weightRadius?: number;
  /**
   * Inner plateau radius (metres) where weight = 1.0 exactly. Between plateau
   * and weightRadius, smoothstep falloff. Defaults to 40% of weightRadius.
   */
  weightPlateau?: number;
}

export interface CharacterSource {
  /** Output filename (without extension) — becomes public/assets/models/<id>.glb */
  id: string;
  /**
   * Absolute path to source asset. `.fbx` runs through Blender's export_mesh.py
   * (T-pose bake + skin export). `.glb` is copied directly to <id>_mesh.glb,
   * skipping the Blender step (use when the GLB already has T-pose rest + skin).
   */
  source: string;
  /** Extra bones injected into the mesh GLB after FBX export (e.g. jiggle bones). */
  injectBones?: readonly InjectedBone[];
  /**
   * Rotation around world X axis (degrees) applied to the mesh GLB after copy/export.
   * Use -90 for Z-up source GLBs that need to align with Y-up Mixamo runtime.
   */
  preRotateXDeg?: number;
  /**
   * Translate mesh so the lowest vertex sits at Y=0 (feet on ground).
   * Useful for source GLBs with origin at center of mass instead of at feet.
   */
  autoGround?: boolean;
}

export const CHARACTERS: CharacterSource[] = [
  {
    id: 'beano',
    source: path.join(ASSETS_SOURCE, 'beano.fbx'),
  },
  {
    id: 'mita',
    source: path.join(ASSETS_SOURCE, 'mita.fbx'),
    // Jiggle bones + weights added manually in assets/source/mita.blend
    // (see Breast_Jiggle_L/R in armature). No auto-inject needed.
  },
  {
    id: 'handyc',
    source: path.join(ASSETS_SOURCE, 'handyc.glb'),
    // GLB exported Z-up (Blender native) — rotate -90° X to align Y-up runtime.
    preRotateXDeg: -90,
    // Origin at torso, not feet — lift so lowest vert sits at ground.
    autoGround: true,
  },
];
