/**
 * Build-time character source list — input FBXs the pipeline ingests.
 * Runtime metadata (scale, display name, thumbnails, etc.) lives in
 * src/fighter/characters.ts and is applied at runtime, not baked into GLBs.
 *
 * Each entry produces `public/assets/models/<id>.glb` via `bun run build:character`.
 *
 * Requirements for the input FBX:
 *   - Mixamo-rigged (bone names prefixed with `mixamorig:`)
 *   - T-pose action available (Mixamo's `mixamo.com` action at frame 1)
 *   - Weights auto-generated by mixamo.com
 */

import path from 'node:path';

const ASSETS_SOURCE = path.join(import.meta.dir, '..', 'assets', 'source');

export interface InjectedBone {
  name: string;
  parent: string;
  /** Head position in mesh-local space (metres) */
  head: [number, number, number];
  /** Tail position in mesh-local space (metres) */
  tail: [number, number, number];
  /**
   * If set, verts within this radius (metres) of the bone head get skin
   * weight via smoothstep falloff (partition of unity — all other bone
   * weights scale by 1-w so this bone dominates at center).
   * Omit for pure procedural helper bones with no mesh deformation.
   */
  weightRadius?: number;
  /**
   * Inner plateau radius (metres) where weight = 1.0 exactly. Between plateau
   * and weightRadius, smoothstep falloff. Defaults to 40% of weightRadius.
   */
  weightPlateau?: number;
}

export interface CharacterSource {
  /** Output filename (without extension) — becomes public/assets/models/<id>.glb */
  id: string;
  /**
   * Absolute path to source asset. `.fbx` runs through Blender's export_mesh.py
   * (T-pose bake + skin export). `.glb` is copied directly to <id>_mesh.glb,
   * skipping the Blender step (use when the GLB already has T-pose rest + skin).
   */
  source: string;
  /** Extra bones injected into the mesh GLB after FBX export (e.g. jiggle bones). */
  injectBones?: readonly InjectedBone[];
  /**
   * Rotation around world X axis (degrees) applied to the mesh GLB after copy/export.
   * Use -90 for Z-up source GLBs that need to align with Y-up Mixamo runtime.
   */
  preRotateXDeg?: number;
  /**
   * Translate mesh so the lowest vertex sits at Y=0 (feet on ground).
   * Useful for source GLBs with origin at center of mass instead of at feet.
   */
  autoGround?: boolean;
  /**
   * Per-clip ground corrections applied after retargeting.
   *
   * After retargeting UAL animations onto a Mixamo skeleton, proportional
   * differences between rigs (UAL vs Mixamo bone lengths) cause the character
   * to float above or sink below Y=0 during ground-contact poses (death, crouch,
   * ground-sit). Each value is the amount to subtract from every Hips.position.y
   * keyframe in that clip — positive = character was floating (shift down),
   * negative = character was sinking (shift up).
   *
   * Computed per character via Blender FK analysis:
   *   correction = min_world_Y_at_contact_frame - idle_floor_reference
   *
   * Only clips where abs(correction) > 5mm need entries.
   */
  groundCorrections?: Record<string, number>;
}

export const CHARACTERS: CharacterSource[] = [
  {
    id: 'beano',
    source: path.join(ASSETS_SOURCE, 'beano.fbx'),
    // Computed via Blender FK analysis (scripts/compute_ground_corrections.py):
    // correction = min_world_Y_at_contact_frame - idle_floor_reference
    groundCorrections: {
      Death01:              0.1803,
      Death02:              0.2511,
      LiftAir_Fall_Impact:  0.2105,
      GroundSit_Enter:      0.2211,
      GroundSit_Idle_Loop:  0.2211,
      GroundSit_Exit:       0.2211,
      Crouch_Idle_Loop:     0.0787,
      Crouch_Enter:         0.0811,
      Crouch_Exit:          0.0811,
      Crouch_Fwd_Loop:      0.0517,
      Crouch_Bwd_Loop:      0.0082,
    },
  },
  {
    id: 'mita',
    source: path.join(ASSETS_SOURCE, 'mita.fbx'),
    // Jiggle bones + weights added manually in assets/source/mita.blend
    // (see Breast_Jiggle_L/R in armature). No auto-inject needed.
    // Computed via Blender FK analysis (scripts/compute_ground_corrections.py):
    groundCorrections: {
      Death01:              0.1315,
      Death02:             -0.5155,
      GroundSit_Enter:      0.2075,
      GroundSit_Idle_Loop:  0.2054,
      GroundSit_Exit:       0.2075,
      Crouch_Idle_Loop:     0.1285,
      Crouch_Enter:         0.1371,
      Crouch_Exit:          0.1372,
      Crouch_Fwd_Loop:      0.0806,
      Crouch_Bwd_Loop:      0.0569,
      Fixing_Kneeling:     -0.2561,
      Slide_Start:          0.0407,
    },
  },
  {
    id: 'handyc',
    source: path.join(ASSETS_SOURCE, 'handyc.glb'),
    // GLB exported Z-up (Blender native) — rotate -90° X to align Y-up runtime.
    preRotateXDeg: -90,
    // Origin at torso, not feet — lift so lowest vert sits at ground.
    autoGround: true,
    // Computed via Blender FK analysis (scripts/compute_ground_corrections.py):
    groundCorrections: {
      Death01:              0.0660,
      Death02:              0.1778,
      LiftAir_Fall_Impact:  0.0701,
      GroundSit_Enter:      0.0763,
      GroundSit_Idle_Loop:  0.0763,
      GroundSit_Exit:       0.0763,
      Crouch_Idle_Loop:     0.0395,
      Crouch_Enter:         0.0399,
      Crouch_Exit:          0.0399,
      Crouch_Fwd_Loop:      0.0385,
      Crouch_Bwd_Loop:     -0.0058,
      Slide_Start:         -0.0326,
    },
  },
  {
    id: 'hanna',
    source: path.join(ASSETS_SOURCE, 'hanna.glb'),
    // Mixamo-rigged GLB, Y-up, feet already at Y=0.
    // export_mesh.py bakes the T-pose rest, producing armature scale=1.0 like beano/mita.
    // Computed via Blender FK analysis (scripts/compute_ground_corrections.py):
    groundCorrections: {
      Death01:              -0.2492,
      Death02:              -0.1582,
      LiftAir_Fall_Impact:  -0.2565,
      GroundSit_Enter:      -0.2385,
      GroundSit_Idle_Loop:  -0.2389,
      GroundSit_Exit:       -0.2385,
      Crouch_Idle_Loop:     -0.1122,
      Crouch_Enter:         -0.1123,
      Crouch_Exit:          -0.1123,
      Crouch_Fwd_Loop:      -0.1261,
      Crouch_Bwd_Loop:      -0.1713,
      Fixing_Kneeling:      -0.1745,
      Slide_Start:          -0.3087,
    },
  },
];
